### ISSUE TITLE
library output support for armeabi-v7a ?

### ISSUE THREAD

**Issue by ghost** [rust-windowing/android-rs-glue#123] opened 2017-01-22 19:34 UTC
Dear tomaka,
When will you add support for armeabi-v7a architecture ? 
We need it so much.
Thanks.

**Comment by dten** [comment] 2017-02-18 18:59
unless I misunderstand you can do this now by specifying build targets in your Cargo.toml

```[package.metadata.android]
build_targets = [ "armv7-linux-androideabi" ]
```

**Comment by davll** [comment] 2017-09-13 03:00
It's required to pass `-march=armv7-a` to `arm-linux-androideabi-gcc` to generate ARMv7a code instead of ARMv6.

**Comment by siriux** [comment] 2018-01-18 19:49
I'm trying to use armv7, and all the options seem to be working (if I add the build target, the -march=armv7-a option is automatically added) but I still get linking errors.

android-rs-glue/examples/basic/target/armv7-linux-androideabi/debug/deps/example-5e3c12e16b8a2e10.example2.rcgu.o: requires unsupported dynamic reloc R_ARM_THM_MOVW_ABS_NC; recompile with -fPIC

On arm-linux-androideabi I managed to fix the linking error using the no-pie option, but on armv7 I cannot get it to work even with: 
RUSTFLAGS='-C relocation-model=dynamic-no-pic -C link-args=-no-pie -C link-args=-fPIC' cargo apk run

@talhazengin @dten @davll does armv7 work for you? Is it even supposed to work right now?

Maybe the problem is related to this rust issue: https://github.com/rust-lang/rust/issues/40145

Thanks

**Comment by siriux** [comment] 2018-01-19 13:08
I finally got it to work !

The good flags are: 
RUSTFLAGS='-C relocation-model=pic -C link-args=-no-pie -C link-args=-Wl,-Bsymbolic'

**Comment by mb64** [comment] 2019-07-30 17:51
It seems this was fixed by #170.  But even if it wasn't, #223 fixes it.

**Closed by mb64** 2019-07-30 17:51 UTC
Labels: enhancement
