### ISSUE TITLE
pressing the back button, and then reopening causes hang

### ISSUE THREAD

**Issue by tiby312** [rust-windowing/android-rs-glue#172] opened 2018-01-28 01:42 UTC
Pressing the android "back" button, and then opening the app again either by icon, or process list, causes the app to hang, or say "app has stopped"

**Comment by tomaka** [comment] 2018-01-29 10:48
That is unfortunately a consequence of the bad model of execution of winit.

**Comment by tiby312** [comment] 2018-01-30 10:12
Hmm this also happens with the basic example even without using winit.

**Comment by tomaka** [comment] 2018-01-30 10:53
Yes, this design was more or less designed in order to be used directly by winit (or rather glutin at the time when this crate was designed). Therefore the design decisions of winit/glutin impacted it in a negative way.

**Comment by mb64** [comment] 2019-07-11 03:50
The main problem here is that Android is free to call `onDestroy()`, followed by `onCreate()`, without re-loading the library.  This leads to `main()` being called twice, which rust really hates, complaining about e.g. trying to write to stdout after shutdown, along with other things.

I'm currently working on the EventLoop 2.0 Android implementation, and as part of that re-writing a lot of the glue.  This includes changes such as a local version of `android_native_app_glue`, and potential modifications to it open up more possibilities for solving this issue.  I have two proposed solutions:

### Don't require the thread to die during `onDestroy()`

This would entail checking if it's alive in `onCreate()` and acting accordingly.

**Pros:** `main()` gets to keep running when possible
**Cons:** It feels wrong to not destroy things during `onDestroy`.  Also, it can never send the Winit `LoopDestroyed` event (because it's impossible to know if it'll actually be destroyed)

### `dlopen()` and `dlclose()` the Rust code during `onCreate()` and `onDestroy()`

Essentially resetting the static data between runs of `main()`.

**Pros:** It seems more consistent to say that `onCreate()` always calls `main()`, rather than "it sometimes does, sometimes doesn't."
**Cons:** [Weird `dlopen()` hackery](https://stackoverflow.com/a/15721061) because it's Android

I'm curious to know which of these people think is best, or if you have other suggestions.

**Comment by mb64** [comment] 2019-07-30 18:08
This is fixed by #223, which calls `fn main()` directly instead of through Rust's startup glue.

**Closed by mb64** 2019-07-30 18:08 UTC
Labels: bug
